from kivy.uix.widget import Widget
from kivy.uix.image import Image
from kivy.uix.floatlayout import FloatLayout

from typing import Tuple, Any


class ClockArm(Widget):
    def __init__(self, size:Tuple[int, int], color:Tuple[float, float, float, float]=...):
        self.image: Image = ...
        self.radius: int = ...
        ...

    def update(self, _:Any=...) -> None:
        ...
    def rotate(self, angle:float) -> None:
        ...
    def set_angle(self, angle:float) -> None:
        ...
    def get_widget(self) -> FloatLayout:
        ...
